language: csharp

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview4-004233
      env: BUILD_NAME=linux
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      env: BUILD_NAME=docker
    - os: osx # OSX 10.12
      osx_image: xcode7.3.1
      env: BUILD_NAME=osx

services:
  - docker

before_script:
  - .travis/$BUILD_NAME/init.sh

script:
  - .travis/$BUILD_NAME/test.sh

after_script:
  - .travis/$BUILD_NAME/teardown.sh