language: csharp

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003131
    - os: osx # OSX 10.11
      osx_image: xcode7.2
      dotnet: 1.0.0-preview2-003131

sudo: required

services:
  - docker

before_script:
  - .travis/$TRAVIS_OS_NAME/init.sh
  - dotnet restore

script:
  - dotnet build -f netcoreapp1.0 src/tarantool.client
  - .travis/$TRAVIS_OS_NAME/test.sh