language: csharp

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003131
    - os: osx # OSX 10.11
      osx_image: xcode7.2
      dotnet: 1.0.0-preview2-003131

sudo: required

services:
  - docker

before_script:
  - dotnet restore
  - docker -v
  - docker-compose down
  - docker-compose up -d
  - cd samples/docker-compose && docker-compose down
  - cd samples/docker-compose && docker-compose up -d --build

script:
  - dotnet build -f netcoreapp1.0 src/tarantool.client
  - dotnet test tests/tarantool.client.tests
  - curl --fail http://localhost:5000