version: 0.0.{build}
skip_tags: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

configuration:
  - Release

matrix:
  fast_finish: false

init:
  - git config --global core.autocrlf true
  - ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

before_build:
  - appveyor-retry dotnet restore -v Minimal

build_script:
  - dotnet build "src\tarantool.client" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
  - dotnet build "tests\tarantool.client.tests" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%

after_build:
  - rm -rf tests\tarantool.client.tests\bin tests\tarantool.client.tests\obj
  - dotnet pack "src\tarantool.client" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts

artifacts:
  - path: artifacts\**\*.*
