version: '2'

services:
  tarantool-client:
    build: .
    command: dotnet test -c Release tests/progaudi.tarantool.tests/progaudi.tarantool.tests.csproj
    environment:
        TARANTOOL_REPLICATION_SOURCE: "tarantool:3301"
    links:
        - tarantool