version: '2'

services:

  tarantool-client:
    build: .
    command: /app/scripts/test-netcore.sh
    environment:
        TARANTOOL_REPLICATION_SOURCE: "tarantool:3301"
    links:
        - tarantool
        - redis

  redis:
    image: redis:3.0-alpine
    command: redis-server
    ports:
      - 6379:6379