parameters:
  netcore1Global: true

steps:
- task: DotNetCoreCLI@2
  displayName: dotnet build
  inputs:
    command: build
    projects: progaudi.tarantool.sln
    arguments: -c Release
    verbosityRestore: minimal

- task: Bash@3
  displayName: set version variable
  inputs:
    targetType: inline
    script: echo "##vso[task.setvariable variable=NugetPackageVersion]$(git describe --tags | sed 's/-/./')"

- task: DotNetCoreCLI@2
  displayName: pack nuget package
  inputs:
    command: pack
    versioningScheme: byEnvVar
    versionEnvVar: NugetPackageVersion
    arguments: --no-build -c Release /property:PackageOutputPath=$(Build.ArtifactStagingDirectory)
    verbosityPack: minimal
